name: Build NodeJS Images - DockerHub
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - genric/nodejs/*
jobs:
  push:
    name: "images:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          #- 12 # NodeJS 12 is EOL (End of Life)
          #- 14 # NodeJS 14 is EOL (End of Life)
          #- 15 # NodeJS 15 is EOL (End of Life)
          - 16
          - 17
          - 18
          - 19
          - "20"
          - 21
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./genric/nodejs
          file: ./genric/nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tresthost/images:nodejs_${{ matrix.tag }}
