name: Build Python Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - genric/python/**
jobs:
  push:
    name: "images:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./genric/python
          file: ./genric/python/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/tresthost/images:python_${{ matrix.tag }}
            tresthost/images:python_${{ matrix.tag }}
